version: 0.2

phases:  
  install:
    commands:
     - echo "Nothing to install"
  build:
    commands:
      - aws s3 cp index.html s3://blue-may-2023-cicd-beta/index.html --acl public-read

      - if [ "$CODEBUILD_WEBHOOK_EVENT" == "PULL_REQUEST_MERGED" ]  ; 
        then aws s3 cp index.html s3://blue-may-2023-cicd-prod/index.html --acl public-read; fi